//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactureIdecEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneFacture
    {
        public int Id { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public Nullable<int> FactureId { get; set; }
        public int Quantite { get; set; }
        public decimal Montant { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Facture Facture { get; set; }
    }
}
